### ISSUE TITLE
Staging folder not created

### ISSUE THREAD

**Issue by nmarks413** [domenic/worm-scraper#27] opened 2021-01-27 19:08 UTC
I ran -o Downloads, as I downloaded worm-scraper in users/myusername. The program then said, after downloading all files, Error: ENOENT: no such file or directory, rmdir 'C:\Users\myusername\staging\worm\OEBPS\chapters'. I ran the program again, the last interlude was downloaded, and the same error occurred. I then ran  npm -g worm-scraper, and the issue persisted. I then created the directory, and everything worked fine. I would suggest using fs to see if the file exists, and if it does not, create it.

**Comment by domenic** [comment] 2021-01-27 19:11
Thanks. Can you provide the full sequence of commands you ran, so that I can reproduce the problem locally? Is it just

```
worm-scraper -o Downloads
```

?

**Comment by nmarks413** [comment] 2021-01-27 20:17
yes

**Comment by domenic** [comment] 2021-01-30 22:51
I was not able to reproduce this. The steps I took were:

```
cd %Temp%
mkdir ws
cd ws
npm install -g worm-scraper
worm-scraper -o Downloads
```

The program ran with no problems and produced a new epub (named `Downloads`, instead of the default name `Worm.epub`).

It sounds like you did some kind of install that was not `npm install -g worm-scraper`, which might have messed things up. Since that's not supported, I'll close this, since it does not indicate a bug in the program, but rather some weird state you got your system into.

But if you can reproduce the problem using steps similar to the ones I posted, then let me know and I can reopen and investigate.

**Closed by domenic** 2021-01-30 22:51 UTC
